apiVersion: v2
name: memgraph-lab
home: https://memgraph.com/
type: application
# Chart version, should be incremented each time the chart changes, including appVersion.
version: 0.1.7
# Version number of the docker image memgraph/lab.
# Use it with quotes.
appVersion: "3.2.0"
description: Memgraph Lab Helm Chart
keywords:
- graph
- database
- cypher
- analytics
icon: https://public-assets.memgraph.com/memgraph-logo/logo-large.png
sources:
- https://github.com/memgraph/memgraph
maintainers:
- name: Memgraph
  email: tech@memgraph.com
