apiVersion: v2
name: memgraph
home: https://memgraph.com/
type: application
version: 0.2.11
appVersion: "3.6.2"
description: MemgraphDB Helm Chart
keywords:
- graph
- database
- cypher
- analytics
icon: https://public-assets.memgraph.com/memgraph-logo/logo-large.png
sources:
- https://github.com/memgraph/memgraph
maintainers:
- name: Memgraph
  email: tech@memgraph.com
